### ISSUE TITLE
Script kinda works

### ISSUE THREAD

**Issue by StampingAround** [CPietro/vrp_hud_inventory#1]
Hi i have just tested it on my server. It seems like i can make it operational or something like it, whenever you use an item a debug string comes in console. You cannot trash items and you comment on fivem for making trunks work does however not work. IDK if im just plain stupid or there is issues with this

**Comment by CPietro** [comment]
Hi, the only confirmed issue with this inventory is with ammo loading. I am fully able to trash items and get trunks working. Please take a look at the README file.
